// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: websocket_delivery.proto

package grpcapi

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnectionIds []string               `protobuf:"bytes,2,rep,name=connection_ids,json=connectionIds,proto3" json:"connection_ids,omitempty"`
	Notification  *Notification          `protobuf:"bytes,3,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryRequest) Reset() {
	*x = DeliveryRequest{}
	mi := &file_websocket_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRequest) ProtoMessage() {}

func (x *DeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRequest.ProtoReflect.Descriptor instead.
func (*DeliveryRequest) Descriptor() ([]byte, []int) {
	return file_websocket_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeliveryRequest) GetConnectionIds() []string {
	if x != nil {
		return x.ConnectionIds
	}
	return nil
}

func (x *DeliveryRequest) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ActionUrl     string                 `protobuf:"bytes,5,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_websocket_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_websocket_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

var File_websocket_delivery_proto protoreflect.FileDescriptor

const file_websocket_delivery_proto_rawDesc = "" +
	"\n" +
	"\x18websocket_delivery.proto\x12\x16messenger.websocket.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x9b\x01\n" +
	"\x0fDeliveryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0econnection_ids\x18\x02 \x03(\tR\rconnectionIds\x12H\n" +
	"\fnotification\x18\x03 \x01(\v2$.messenger.websocket.v1.NotificationR\fnotification\"\x81\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"action_url\x18\x05 \x01(\tR\tactionUrl2_\n" +
	"\x11WebSocketDelivery\x12J\n" +
	"\aDeliver\x12'.messenger.websocket.v1.DeliveryRequest\x1a\x16.google.protobuf.EmptyBQZOgithub.com/douglasvolcato/messager-architecture-challenge/internal/grpc;grpcapib\x06proto3"

var (
	file_websocket_delivery_proto_rawDescOnce sync.Once
	file_websocket_delivery_proto_rawDescData []byte
)

func file_websocket_delivery_proto_rawDescGZIP() []byte {
	file_websocket_delivery_proto_rawDescOnce.Do(func() {
		file_websocket_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_delivery_proto_rawDesc), len(file_websocket_delivery_proto_rawDesc)))
	})
	return file_websocket_delivery_proto_rawDescData
}

var file_websocket_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_websocket_delivery_proto_goTypes = []any{
	(*DeliveryRequest)(nil), // 0: messenger.websocket.v1.DeliveryRequest
	(*Notification)(nil),    // 1: messenger.websocket.v1.Notification
	(*empty.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_websocket_delivery_proto_depIdxs = []int32{
	1, // 0: messenger.websocket.v1.DeliveryRequest.notification:type_name -> messenger.websocket.v1.Notification
	0, // 1: messenger.websocket.v1.WebSocketDelivery.Deliver:input_type -> messenger.websocket.v1.DeliveryRequest
	2, // 2: messenger.websocket.v1.WebSocketDelivery.Deliver:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_websocket_delivery_proto_init() }
func file_websocket_delivery_proto_init() {
	if File_websocket_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_delivery_proto_rawDesc), len(file_websocket_delivery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_websocket_delivery_proto_goTypes,
		DependencyIndexes: file_websocket_delivery_proto_depIdxs,
		MessageInfos:      file_websocket_delivery_proto_msgTypes,
	}.Build()
	File_websocket_delivery_proto = out.File
	file_websocket_delivery_proto_goTypes = nil
	file_websocket_delivery_proto_depIdxs = nil
}
