// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: websocket_delivery.proto

package grpcapi

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebSocketDelivery_Deliver_FullMethodName = "/messenger.websocket.v1.WebSocketDelivery/Deliver"
)

// WebSocketDeliveryClient is the client API for WebSocketDelivery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebSocketDeliveryClient interface {
	Deliver(ctx context.Context, in *DeliveryRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type webSocketDeliveryClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSocketDeliveryClient(cc grpc.ClientConnInterface) WebSocketDeliveryClient {
	return &webSocketDeliveryClient{cc}
}

func (c *webSocketDeliveryClient) Deliver(ctx context.Context, in *DeliveryRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, WebSocketDelivery_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebSocketDeliveryServer is the server API for WebSocketDelivery service.
// All implementations must embed UnimplementedWebSocketDeliveryServer
// for forward compatibility.
type WebSocketDeliveryServer interface {
	Deliver(context.Context, *DeliveryRequest) (*empty.Empty, error)
	mustEmbedUnimplementedWebSocketDeliveryServer()
}

// UnimplementedWebSocketDeliveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebSocketDeliveryServer struct{}

func (UnimplementedWebSocketDeliveryServer) Deliver(context.Context, *DeliveryRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedWebSocketDeliveryServer) mustEmbedUnimplementedWebSocketDeliveryServer() {}
func (UnimplementedWebSocketDeliveryServer) testEmbeddedByValue()                           {}

// UnsafeWebSocketDeliveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebSocketDeliveryServer will
// result in compilation errors.
type UnsafeWebSocketDeliveryServer interface {
	mustEmbedUnimplementedWebSocketDeliveryServer()
}

func RegisterWebSocketDeliveryServer(s grpc.ServiceRegistrar, srv WebSocketDeliveryServer) {
	// If the following call pancis, it indicates UnimplementedWebSocketDeliveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebSocketDelivery_ServiceDesc, srv)
}

func _WebSocketDelivery_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSocketDeliveryServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSocketDelivery_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSocketDeliveryServer).Deliver(ctx, req.(*DeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebSocketDelivery_ServiceDesc is the grpc.ServiceDesc for WebSocketDelivery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebSocketDelivery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messenger.websocket.v1.WebSocketDelivery",
	HandlerType: (*WebSocketDeliveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _WebSocketDelivery_Deliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "websocket_delivery.proto",
}
